# 直接使用一个轻量的基础镜像，不再包含 Node.js
FROM harbor.goertek.com/aihub/nginx-proxy:latest

COPY docker/frontend/nginx.conf /etc/nginx/conf.d/default.conf

# 假设 Jenkins 已经在构建阶段把 dist 生成在项目根目录下
COPY dist /usr/share/nginx/html

# 暴露端口
EXPOSE 80

# 启动 nginx
CMD ["nginx", "-g", "daemon off;"]
