# # 基础镜像
# # FROM  harbor.gitp.docker.local:30080/jdk/oraclejdk:1.8.0_333-centos7.9.2009
# FROM  harbor.goertek.com/base/oraclejdk:18.0.1.1-centos7.9.2009-UTC8
# #FROM  harbor.goertek.com/base/openjdk:11.0.16-jdk-arthas-3.6.7-UTC-8
# # author
# MAINTAINER goertek
# ENV TZ Asia/Shanghai
# # 复制jar文件到路径
# COPY ./jar/expert-link-backend-1.0.0.jar /expert-link-backend-1.0.0.jar
# # 启动系统服务
# ENTRYPOINT ["java","-jar","expert-link-backend-1.0.0.jar"]


# 直接使用一个轻量的基础镜像，不再包含 Node.js
FROM harbor.goertek.com/base/nginx-proxy:latest

# 安装必要的运行库和 nginx
# RUN apk add --no-cache libstdc++ nginx

# 设置工作目录
WORKDIR /app

# 关键: 将 Jenkins 工作空间里已经解压好的 Node.js 整个目录复制到镜像内
# 假设 Node.js 被解压到了项目根目录下的 .node/ 文件夹中
# ls
# COPY .node /usr/local/node

# 将构建好的前端产物复制到 nginx 目录
# 假设 Jenkins 已经在构建阶段把 dist 生成在项目根目录下
COPY dist /usr/share/nginx/html

# 设置环境变量，让镜像内的 node 命令可用（如果后续有需要）
# ENV PATH="/usr/local/node/bin:${PATH}"

# 暴露端口
EXPOSE 80

# 启动 nginx
CMD ["nginx", "-g", "daemon off;"]
